name: React

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: client/package-lock.json
            - run: npm ci
              working-directory: client
            - run: CI=false npm run build --if-present
              working-directory: client
            - run: npm test
              working-directory: client

    analyze:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/cache@v4.0.2

            - name: Sonar Scan Front-end
              uses: sonarsource/sonarqube-scan-action@v4.0.0
              with:
                  projectBaseDir: client
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
